#!/bin/bash
set -e
base_dir=${1:-.}

for changes_file in "${base_dir}"/*.changes ; do
  if ! [ -w "${changes_file}" ] ; then
    echo "${changes_file} not found or no write permissions" >&2
    exit 2
  fi

  if ! grep -q 'Priority:' "${changes_file}" ; then
    sed -i '/Architecture: source/a\Priority: optional' "${changes_file}"
    echo "*** Added Priority header to ${changes_file} ***"
  fi
done
